# Generated by Django 4.1.6 on 2023-02-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20180507_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('adanger', 'Difficulty High'), ('bwarning', 'Difficulty Medium'), ('csuccess', 'Difficulty Low')], default='adanger', max_length=30),
        ),
    ]
